game.AddParticles( "particles/lambdatf2_explosion.pcf" )
game.AddParticles( "particles/lambdatf2_rockettrail.pcf" )
game.AddParticles( "particles/lambdatf2_flamethrower.pcf" )
game.AddParticles( "particles/lambdatf2_crit.pcf" )
game.AddParticles( "particles/lambdatf2_rocketbackblast.pcf" )
game.AddParticles( "particles/lambdatf2_item_fx.pcf" )

PrecacheParticleSystem( "rockettrail" )
PrecacheParticleSystem( "flamethrower" )
PrecacheParticleSystem( "ExplosionCore_MidAir" )
PrecacheParticleSystem( "ExplosionCore_Wall" )
PrecacheParticleSystem( "crit_text" )
PrecacheParticleSystem( "minicrit_text" )
PrecacheParticleSystem( "rocketbackblast" )
PrecacheParticleSystem( "peejar_impact" )
PrecacheParticleSystem( "peejar_drips" )
PrecacheParticleSystem( "peejar_drips_milk" )